# Schema for the configuration files of the node module.

# todo add setttings

eform.type.*:
  type: config_entity
  label: 'EForm type'
  mapping:
    name:
      type: label
      label: 'Name'
    type:
      type: string
      label: 'Machine-readable name'
    description:
      type: text
      label: 'Description'
    help:
      type: text
      label: 'Explanation or submission guidelines'
    form_status:
      type: string
      label: 'Form Status'
    resubmit_action:
      type: string
      label: 'Resubmit Action'
    disallow_text:
          type: mapping
          label: 'Disallow Text'
          mapping:
            format:
              type: string
              label: 'Format'
            value:
              type: string
              label: 'Value'
    roles:
      type: sequence
      sequence:
        type: string
        label: 'Roles'
    preview_page:
      type: boolean
      label: 'Preview Page'
    submission_page_title:
      type: string
      label: 'Submission Page Title'
    submission_text:
      type: mapping
      label: 'Submission Text'
      mapping:
        format:
          type: string
          label: 'Format'
        value:
          type: string
          label: 'Value'
    draftable:
          type: boolean
          label: 'Draftable'

